name: Final_project

on:
  push:
    branches: [ "main" ]
env:
    First_name: "Einat"
    Relis_name: "First.name-${{github.sha}}
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
        run: echo "Hello"
                  run: lsb_release -a
                        run: First_name: "-${{ github.sha }}"
