name: My Workflow

on:
  push:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Do multiple things
      run: |
        echo "Running command 1"
        echo "Running command 2"
        echo "Running command 3"
