name: final_project
env:
  First_name: "Einat"
  Relis_name: " First.name-${{ github.sha}}

on:
  push:
    branches:
      -main
jobs:
  job1:
    runs-on: ubunto-latest
    steps:
      -name: print hello
      run: echo "Hello"
      -name: print ubunto version
      run: aws --version
      -name: commit github sha
      run: First_name: "-$({ github.sha })"
  job2:
    runs-on: ubunto-latest
    needs: [job1]
    steps:
      -name: cat1
      run: cat 1.txt
      name: cat2
      run: cat 2.txt
      -name: run test.sh
      run:|
        chmode777 .test.sh
        ./test.sh
  job3:
    runs-on: ubunto-latest
    needs: [job2]
    env:
      env.Last_name: "Barak"
    steps:  
      -name: general env
      run: echo " application name ${{ env.First_name }}"
      -name: local env
      run: echo " $Last_name "
      -name: secret1
      run: echo ${{ secrets.MOBILE_NUM }}
    
