name: Final_project
on:
  push:
    branches:
      - main
env:
  First_name: "Einat"
jobs:
  Job1:
    runs-on: ubunto-latest
    steps:
        - name: Hello
          run: echo "hello"
        - name: version
          run: lsb_release -r
        - name: sha
          run: echo "First_name:-${{ github.sha }}"
  Job2:
    runs-on: ubunto-latest
    steps:
      - name: cat1
        run: cat 1.txt
      - name: cat2
        run: cat 2.txt
      - name: run test.sh
        run: |
              chmode 777 test.sh
              ./test.sh
  Job3:
      runs-on: ubunto-latest
      env:
          env.Last_name: "Barak"
      steps:
         - name: general env
           run: echo " application name ${{ env.First_name }}"
         - name: local env
           run: echo "$Last_name"
         - name: secret1
           run: echo ${{ secrets.MOBILE_NUM }}
