name: final_project
env:
  First_name: "Einat"
  Relis_name: " First.name-${{ github.sha}}

on:
  push:
    branches:
      -main
jobs:
  job1:
    runs-on: ubunto-latest
    steps:
       run: echo "Hello"
